import type { Language } from '@/types'

export const translations = {
  en: {
    appName: 'HeartConnect',
    tagline: 'Love knows no distance',
    login: 'Sign In',
    signup: 'Create Account',
    email: 'Email',
    password: 'Password',
    displayName: 'Your Name',
    continueWithGoogle: 'Continue with Google',
    createRoom: 'Create Private Room',
    joinRoom: 'Join with Code',
    roomCode: 'Room Code',
    invitePartner: 'Invite Partner',
    copyLink: 'Copy Invite Link',
    shareCode: 'Share Room Code',
    chat: 'Chat',
    games: 'Games',
    online: 'Online',
    offline: 'Away',
    typing: 'typing...',
    sendMessage: 'Send a message...',
    voiceNote: 'Hold to record',
    reactions: 'React',
    darkMode: 'Dark Mode',
    lightMode: 'Light Mode',
    language: 'Language',
    dashboard: 'Our Space',
    yourRoom: 'Your Room',
    waitingForPartner: 'Waiting for your partner...',
    partnerJoined: 'Your partner joined! 💕',
    gameMode: {
      'truth-dare': 'Truth & Dare',
      'deep-questions': 'Deep Questions',
      'couple-quiz': 'Couple Quiz',
      'daily-challenge': 'Daily Challenge',
      'flirty-cards': 'Flirty Cards',
      'love-language': 'Love Language',
      'future-planning': 'Future Together',
    },
    category: {
      cute: '🌸 Cute',
      romantic: '💗 Romantic',
      flirty: '😘 Flirty',
      deep: '💭 Deep',
      challenge: '🎯 Challenge',
    },
    nextQuestion: 'Next',
    truth: 'Truth',
    dare: 'Dare',
    logout: 'Sign Out',
    profile: 'Profile',
    missYou: 'Missing you right now 💕',
    sendHug: 'Send a Hug',
    hugSent: 'Hug sent! 🤗',
  },
  hi: {
    appName: 'HeartConnect',
    tagline: 'प्यार में दूरी कोई मायने नहीं रखती',
    login: 'साइन इन करें',
    signup: 'अकाउंट बनाएं',
    email: 'ईमेल',
    password: 'पासवर्ड',
    displayName: 'आपका नाम',
    continueWithGoogle: 'Google से जारी रखें',
    createRoom: 'प्राइवेट रूम बनाएं',
    joinRoom: 'कोड से जॉइन करें',
    roomCode: 'रूम कोड',
    invitePartner: 'पार्टनर को इनवाइट करें',
    copyLink: 'इनवाइट लिंक कॉपी करें',
    shareCode: 'रूम कोड शेयर करें',
    chat: 'चैट',
    games: 'गेम्स',
    online: 'ऑनलाइन',
    offline: 'अनुपस्थित',
    typing: 'टाइप कर रहे हैं...',
    sendMessage: 'संदेश लिखें...',
    voiceNote: 'रिकॉर्ड करने के लिए दबाएं',
    reactions: 'रिएक्ट करें',
    darkMode: 'डार्क मोड',
    lightMode: 'लाइट मोड',
    language: 'भाषा',
    dashboard: 'हमारी जगह',
    yourRoom: 'आपका रूम',
    waitingForPartner: 'पार्टनर का इंतजार है...',
    partnerJoined: 'आपका पार्टनर जुड़ गया! 💕',
    gameMode: {
      'truth-dare': 'सच और साहस',
      'deep-questions': 'गहरे सवाल',
      'couple-quiz': 'कपल क्विज़',
      'daily-challenge': 'डेली चैलेंज',
      'flirty-cards': 'फ्लर्टी कार्ड्स',
      'love-language': 'प्रेम भाषा',
      'future-planning': 'हमारा भविष्य',
    },
    category: {
      cute: '🌸 प्यारा',
      romantic: '💗 रोमांटिक',
      flirty: '😘 फ्लर्टी',
      deep: '💭 गहरा',
      challenge: '🎯 चैलेंज',
    },
    nextQuestion: 'अगला',
    truth: 'सच',
    dare: 'साहस',
    logout: 'साइन आउट',
    profile: 'प्रोफाइल',
    missYou: 'अभी तुम्हारी बहुत याद आ रही है 💕',
    sendHug: 'गले लगाओ',
    hugSent: 'गले लगाया! 🤗',
  },
  or: {
    appName: 'HeartConnect',
    tagline: 'Prema re duri kono arthа nahi',
    login: 'Sign In kara',
    signup: 'Account banao',
    email: 'Email',
    password: 'Password',
    displayName: 'Tumara naam',
    continueWithGoogle: 'Google re chalija',
    createRoom: 'Private Room banao',
    joinRoom: 'Code diya join kara',
    roomCode: 'Room Code',
    invitePartner: 'Partner ku invite kara',
    copyLink: 'Invite link copy kara',
    shareCode: 'Room code share kara',
    chat: 'Chat',
    games: 'Games',
    online: 'Online achi',
    offline: 'Nahi achi',
    typing: 'type karucha...',
    sendMessage: 'Kichhi likhna...',
    voiceNote: 'Record karibaku dhara',
    reactions: 'React kara',
    darkMode: 'Dark Mode',
    lightMode: 'Light Mode',
    language: 'Bhasha',
    dashboard: 'Amara jagah',
    yourRoom: 'Tumara Room',
    waitingForPartner: 'Partner ku apekhya karucha...',
    partnerJoined: 'Tumara partner aasi gala! 💕',
    gameMode: {
      'truth-dare': 'Satya O Sahas',
      'deep-questions': 'Gehela Prashna',
      'couple-quiz': 'Couple Quiz',
      'daily-challenge': 'Daily Challenge',
      'flirty-cards': 'Flirty Cards',
      'love-language': 'Prema Bhasha',
      'future-planning': 'Amara Bhabisyat',
    },
    category: {
      cute: '🌸 Pyara',
      romantic: '💗 Romantic',
      flirty: '😘 Flirty',
      deep: '💭 Gehela',
      challenge: '🎯 Challenge',
    },
    nextQuestion: 'Parei',
    truth: 'Satya',
    dare: 'Sahas',
    logout: 'Sign Out',
    profile: 'Profile',
    missYou: 'Ebe tumaku bahut miss karucha 💕',
    sendHug: 'Anka pathao',
    hugSent: 'Anka pathagala! 🤗',
  },
}

export function t(key: string, lang: Language): string {
  const keys = key.split('.')
  let obj: Record<string, unknown> = translations[lang] as Record<string, unknown>
  for (const k of keys) {
    if (obj && typeof obj === 'object' && k in obj) {
      obj = obj[k] as Record<string, unknown>
    } else {
      // fallback to English
      obj = translations.en as Record<string, unknown>
      for (const fk of keys) {
        if (obj && typeof obj === 'object' && fk in obj) {
          obj = obj[fk] as Record<string, unknown>
        }
      }
      break
    }
  }
  return typeof obj === 'string' ? obj : key
}
